// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class MLModel1
{
    /// <summary>
    /// model input class for MLModel1.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [ColumnName(@"mpg")]
        public float Mpg { get; set; }

        [ColumnName(@"cylinders")]
        public float Cylinders { get; set; }

        [ColumnName(@"displacement")]
        public float Displacement { get; set; }

        [ColumnName(@"horsepower")]
        public float Horsepower { get; set; }

        [ColumnName(@"weight")]
        public string Weight { get; set; }

        [ColumnName(@"acceleration")]
        public float Acceleration { get; set; }

        [ColumnName(@"model year")]
        public float Model_year { get; set; }

        [ColumnName(@"origin")]
        public float Origin { get; set; }

        [ColumnName(@"car name")]
        public string Car_name { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for MLModel1.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"mpg")]
        public float Mpg { get; set; }

        [ColumnName(@"cylinders")]
        public float Cylinders { get; set; }

        [ColumnName(@"displacement")]
        public float Displacement { get; set; }

        [ColumnName(@"horsepower")]
        public float Horsepower { get; set; }

        [ColumnName(@"weight")]
        public float[] Weight { get; set; }

        [ColumnName(@"acceleration")]
        public float Acceleration { get; set; }

        [ColumnName(@"model year")]
        public float Model_year { get; set; }

        [ColumnName(@"origin")]
        public float Origin { get; set; }

        [ColumnName(@"car name")]
        public float[] Car_name { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }
}
